//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public System.Guid Id { get; set; }
        public string OwnerFullName { get; set; }
        public string OwnerAddress { get; set; }
        public string OwnerPhone { get; set; }
        public string MPSModel { get; set; }
        public string MPSNumber { get; set; }
        public string TrailerNumber { get; set; }
        public string InsurerCompany { get; set; }
        public string InsurerPolicyNumber { get; set; }
        public string InsurerGreenCardNumber { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public string InsurerAgency { get; set; }
        public string InsurerAddress { get; set; }
        public string InsurerPhone { get; set; }
        public string LeaderFullName { get; set; }
        public System.DateTime LeaderBornDate { get; set; }
        public string LeaderAddress { get; set; }
        public string LeaderPhone { get; set; }
        public int LeaderCertificate { get; set; }
        public string LeaderCategory { get; set; }
        public System.DateTime LeaderCertificateValidTo { get; set; }
        public int PolicyNumber { get; set; }
        public string VisibleDamage { get; set; }
        public string AttachFile { get; set; }
        public string Circumstances { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsGuilty { get; set; }
    }
}
