//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health
    {
        public System.Guid Id { get; set; }
        public string FullName { get; set; }
        public string EGN { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int DocumentNumber { get; set; }
        public string IBAN { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string AttachFile { get; set; }
        public int UserId { get; set; }
        public string Company { get; set; }
    }
}
